create or replace TRANSIENT TABLE "DBO".STUDENT_TRANSIENT (
	STUDENT_ID NUMBER(38,0),
	STUDENT_NAME VARCHAR(50),
	STUDENT_AGE NUMBER(38,0)
 "SANDBOX1".""reate or replace TRANSIENT TABLE "DBO".STUDENT_TRANSIENT (
	STUDENT_ID NUMBER(38,0),
	STUDENT_NAME VARCHAR(50),
	STUDENT_AGE NUMBER(38,0)
);
-----------------------------------------------------------------------------
