create or replace TRANSIENT TABLE "DBO".MY_TRANSIENT_TABLE (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 3 noorder,
	FULL_NAME VARCHAR(300),
	AGE NUMBER(38,0),
	ADDRESS VARCHAR(16777216),
	FULL_DEATILS VARCHAR(16777216),
	HOME_ADDRESS VARCHAR(16777216) NOT NULL,
	constraint UNIQUENESS unique (FULL_NAME),
	constraint PK_TRANSIENT_TABLE primary key (ID)
);