create or replace TRANSIENT TABLE "DBO".TESTDATA_UTKAL (
	ID NUMBER(38,0),
	EMPLOYEEID NUMBER(38,0),
	NAME VARCHAR(50),
	EMAIL VARCHAR(50),
	"DimLocation" VARCHAR(15),
	"CountryCode" VARCHAR(50),
	STARTDATE VARCHAR(15),
	ENDDATE DATE,
	ZIPCODE VARCHAR(50),
	SALARY NUMBER(18,0),
	"RiskExpLocation" VARCHAR(50),
	TESTBLANK VARCHAR(10),
	COLUMN_A VARCHAR(1000)
);